version: 0.0
os: linux
files:
  - source: build/libs/server-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/serverJar
ApplicationStart:
  - location: bashScripts/applicationStart.sh
    timeout: 300
    runas: root